## Hex color strings
mute_red      = "#FFCCCB"
mute_blue     = "#ADD8E6"
sea_green     = "#77fc98"
reg_teal      = "#00d4d4"
lite_teal     = "#84cfcf"
lite_ornge    = "#fad096"
reg_magnta    = "#ff5fff"
pale_magnta   = "#fdddff"
lite_magnta   = "#fb8aff"
pale_red      = "#ffdddd"
dark_red      = "#db3052"
lite_red      = "#ff6161"
pale_blue     = "#7dc7ff"
lite_blue     = "#789aff"
dark_blue     = "#1202a8"
hot_green     = "#3fad3d"
dark_green    = "#379435"
hot_purple    = "#c70a95"
lite_purple   = "#cf79f7"
pale_purple   = "#dc9bfa"
dark_purple   = "#a911ba"
rglr_gold     = "#b8a200"
lite_gray     = "#545454"
dark_gray     = "#bebebe"
rglr_cyan     = "#0ec9bd"
success_green = "#0cc984"  
fail_red      = "#ed264e"
reg_salmon    = "#f7847c"

payoff_font   = "TkFixedFont 15"


tests = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L"]
